apiVersion: v1
kind: Service
metadata: 
  name: hello-obs-logs-java-service
  labels:
    app: hello-obs-logs-java
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 8080
  selector:
    app: hello-obs-logs-java
